name: hardwarejunkie
favicon: null
layout_spectrum: 0.66618
typography_spectrum: 0
title: Hardware Tinker
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ff0000'
    - '#f39c12'
    - '#3498db'
    - '#38495a'
  brandStrength: 0.5
  lightness: 0.8125
  saturation: 0.6875
  rhythmicContrast: 1
purpose: []
