name: hardwarejunkie
favicon: null
layout_spectrum: 0.1045844356995076
typography_spectrum: 0.2686943474691361
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ff0000'
    - '#f39c12'
    - '#3498db'
    - '#38495a'
  brandStrength: 0.8383827600628138
  lightness: 0.7726609089877456
  saturation: 0.03717254288494587
  rhythmicContrast: 0.43034721864387393
purpose: []
